language: python

python:
  - '2.6'
  - '2.7'
  - '3.2'
  - '3.3'
  - '3.4'

script: "python setup.py test"

after_success:
  - coveralls

notifications:
  irc:
    channels: "irc.freenode.org#atal-dev"
    on_success: change
    on_failure: change
