language: python

python:
  - '2.6'
  - '2.7'
  - '3.2'
  - '3.3'

before_install:
  - pip install --upgrade coveralls
  - pip install --upgrade coverage
  - mkdir -p /usr/share/nagaram
  - cp wordlists/* /usr/share/nagaram/

script: "nosetests --with-coverage --cover-package=nagaram"

after_success:
  - coveralls

notifications:
  irc:
    channels: "irc.freenode.org#atal-dev"
    on_success: change
    on_failure: change
